### ISSUE TITLE
USB Host low-speed device enumeration

### ISSUE THREAD

**Issue by alexpa940** [CherryUSB/cherryusb_wch#1]
I tried to connect a low-speed keyboard. Initialization does not occur. 
Cherry USB in the log writes that the hub is installed in full-speed mod and setup packet timeout. 
The full-speed keyboard is detected correctly.
I tried changing CONFIG_USBHOST_CONTROL_TRANSFER_TIMEOUT, but it doesn't have any effect.
USB high speed controller ch32v307 was used.

**Comment by alexpa940** [comment]
```
do not find /dev/input0
[I/USB] Dev connect
[I/USB] New full-speed device on Hub 1, Port 1 connected
[I/USB] ep0 reconfigure USB_SPEED_FULL
[I/USB] ep0 reconfigure USB_SPEED_FULL
[I/USB] New device found,idVendor:1a2c,idProduct:4094,bcdDevice:0110
[I/USB] The device has 2 interfaces
[I/USB] Enumeration success, start loading class driver
[I/USB] Loading hid class driver
[I/USB] Ep=81 Attr=03 Mps=8 Interval=10 Mult=00
[I/USB] Register HID Class:/dev/input0
[I/USB] Loading hid class driver
[I/USB] Ep=82 Attr=03 Mps=3 Interval=10 Mult=00
[I/USB] Register HID Class:/dev/input1
[I/USB] pipe->urb is not null
0x00 0x00 0x18 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x18 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
USB_HOST_thread         2               <1%
Runtime stats           7               <1%
MainLoop                3               <1%
IDLE                    299907          99%
usbh_hub                78              <1%
Free heap 92576
[I/USB] Dev remove
[I/USB] pipe->urb is not null
[I/USB] pipe->urb is not null
[I/USB] pipe->urb is not null
[I/USB] pipe->urb is not null
[I/USB] pipe->urb is not null
[I/USB] pipe->urb is not null
[I/USB] Unregister HID Class:/dev/input0
[I/USB] Unregister HID Class:/dev/input1
do not find /dev/input0
do not find /dev/input0
[I/USB] Dev connect
[I/USB] New full-speed device on Hub 1, Port 1 connected
[I/USB] ep0 reconfigure USB_SPEED_FULL
[I/USB] ep0 reconfigure USB_SPEED_FULL
[E/USB] SETUP TIMEOUT
[E/USB] Failed to get full device descriptor,errorcode:-5
[E/USB] Port 1 enumerate fail
```

**Comment by alexpa940** [comment]
Info about connected keyboard
![image](https://user-images.githubusercontent.com/11144042/223824680-f8f0fb4a-3d20-47e6-b67b-3237f95162c9.png)

**Comment by sakumisu** [comment]
I am not sure the v307 details, maybe the port speed get has some problems, the wch official has no demo in host.

**Comment by HaiMianBBao** [comment]
Now you can try enumerating low-speed USB devices. I have updated the code, please update your local repository before testing.

**Comment by alexpa940** [comment]
![image](https://user-images.githubusercontent.com/11144042/231304806-a8dd0842-226f-4be6-8bb8-bbe222104afe.png)
The speed is determined but the handle is not received.

> Now you can try enumerating low-speed USB devices. I have updated the code, please update your local repository before testing.

**Comment by alexpa940** [comment]
![image](https://user-images.githubusercontent.com/11144042/231304949-31904b91-30f7-484f-be38-71c819e27c7b.png)

**Comment by alexpa940** [comment]
Another full-speed keyboard is defined as low-speed. 
And the usb flash drive is defined as low speed.
![image](https://user-images.githubusercontent.com/11144042/231305801-ae5a2496-7fc8-4c4d-8635-b65009b721df.png)

**Comment by HaiMianBBao** [comment]
Thanks for the test. Which usb port are you using, full or high speed? If possible, could you help me test the other usb port?

**Comment by alexpa940** [comment]
Last time I tested ushs.

Now usbfs.
First usbhs noname flash.
![image](https://user-images.githubusercontent.com/11144042/231356118-bfd8937d-ddd9-49fc-9a43-73da1a14ee39.png)

The second USB flash drive transcend usbhs.
![image](https://user-images.githubusercontent.com/11144042/231355084-0fc4035e-5975-4558-b60b-ac9d7787f40b.png)

Some full-speed devices (keyboard and mouse)
![image](https://user-images.githubusercontent.com/11144042/231355285-f141f1ee-e9b4-4fc2-a252-d9fd1b641b8a.png)
![image](https://user-images.githubusercontent.com/11144042/231355506-2c02a68a-cb5a-4082-9aeb-af9259ef70b5.png)

As low-speed device USBAsp
![image](https://user-images.githubusercontent.com/11144042/231355990-4997d5b4-cca5-4227-821d-2f7a5d3f80e8.png)

Old low-speed keyboard
![image](https://user-images.githubusercontent.com/11144042/231356877-da40ace4-c021-4500-bbfc-2b8c5d41f3fe.png)

**Comment by alexpa940** [comment]
Update for usb hs.
As low-speed device USBAsp
![image](https://user-images.githubusercontent.com/11144042/231358218-9f845b4e-c11a-4f2a-9d0a-08e115c52962.png)

The rest is the same as in the message about usbhs - the port speed is always usbls.

**Comment by alexpa940** [comment]
the hs usb host skips the device descriptor part of the connected device
![image](https://user-images.githubusercontent.com/11144042/232318971-6fad946e-837a-4590-8f1c-78457943beaf.png)

**Comment by sakumisu** [comment]
No more support host.
