### ISSUE TITLE
有计划支持CH569吗？

### ISSUE THREAD

**Issue by 0x0fe** [CherryUSB/cherryusb_wch#11]
有计划支持CH569吗？ 特别是 SS HOST, MSD 和 UVC

**Comment by sakumisu** [comment]
非开源不做支持

**Comment by 0x0fe** [comment]
请加我进群，我要你引用 3265649676

**Comment by sakumisu** [comment]
直接加群就可以了

**Comment by 0x0fe** [comment]
我无法加入它要求输入密码

**Comment by sakumisu** [comment]
随便输入

**Comment by 0x0fe** [comment]
不幸的是它拒绝

**Comment by sakumisu** [comment]
你搞错了吧，是群，没有拒绝选项

**Comment by sakumisu** [comment]
642693751

**Comment by 0x0fe** [comment]
![image](https://github.com/CherryUSB/cherryusb_wch/assets/89607149/a3adeff8-7683-4621-9ca1-171922e21c43)
![image](https://github.com/CherryUSB/cherryusb_wch/assets/89607149/33aa2462-95ce-4a38-9cb5-8741fecc9e06)

**Comment by 0x0fe** [comment]
我同事用她的QQ试过了，一样的
