### ISSUE TITLE
Has USB HS devices been tested on CH32V307?

### ISSUE THREAD

**Issue by techlabz** [CherryUSB/cherryusb_wch#2]
I tried using the hid_kbd example, in my project but it failed during usb enumeration. I also tried to compile to get a binary to test directly using make, and I got errors, are you using a specific risc-v compiler I got the latest from xpack. Have these examples been tested by yourself?

![image](https://user-images.githubusercontent.com/42513204/226058865-adc57aab-fbee-428d-9375-0c5dad3cc80f.png)

**Comment by HaiMianBBao** [comment]
I have tested CH32V307 USBHS Device as a keyboard. You may need to remove the const in front of the descriptor. The compiler I used is a compiler modified by wch.

**Comment by sakumisu** [comment]
remove const before your descriptor, wch do not support dma access to flash.
