### ISSUE TITLE
audio_v1_mic_multichan_template not working properly

### ISSUE THREAD

**Issue by nikkov** [CherryUSB/cherryusb_wch#3]
I tried built and test FS audio_v1_mic_multichan_template based [audio_v1_mic_multichan_template ](https://github.com/nikkov/cherryusb_wch/tree/master/examples/usb_device/audio_v1_mic_multichan). 
Enumeration is OK, but recording working only once. First opening device is successfully, I see "open EP" in terminal and 'a' value in data from device. But after stopped and started recording again, I see "open EP" in terminal and errors in USB requests because device not send any data.

**Comment by sakumisu** [comment]
I dont think wch support iso, so do not test audio or video.

**Comment by nikkov** [comment]
I did a some testing and found that usbd_audio_iso_callback never called, so ep_tx_busy_flag is not reset and
```
           while (ep_tx_busy_flag) {
            }

```
in audio_test runs forever

**Comment by sakumisu** [comment]
stop using wch with audio and video.

**Comment by sakumisu** [comment]
I do not think wch is ready for this.

**Comment by sakumisu** [comment]
Just enum for fun.

**Comment by sakumisu** [comment]
If you want to use audio, please select other chips, thanks. I think this issue is done.

**Comment by techlabz** [comment]
I'll send a email to wch and see if isochronous is possible.

**Comment by techlabz** [comment]
A few things, make sure to add USBHS_UIE_ISO_ACT to the interrupt enable register. Then add the interrupt flag in your in the IRQhandler and handle properly. You have to modify the descriptors potentially for USB 2.0 High Speed to work. I have so far got it working with USB 2.0 Full Speed.

![image](https://user-images.githubusercontent.com/42513204/230040958-c9037e23-65e9-4d7b-bc62-0042d39d75b5.png)

**Comment by techlabz** [comment]
@sakumisu @HaiMianBBao 

A lot must have went in this project, good job on the progress so far. Some notes,
I would suggest updating the readme and letting your users know what has actually been tested, what is in progress etc, like a checklist? Also quirks like const and other issues that users may face with this stack with respect to WCH chips. We're shooting in the dark right now.

**Comment by sakumisu** [comment]
Thank you, these have added.
