### ISSUE TITLE
Multiple USB instances on MCU with multiple USB ports

### ISSUE THREAD

**Issue by aurimasniekis** [CherryUSB/cherryusb_wch#4]
I recently reviewed the code in a relatively short amount of time, but during my examination, I did not come across any specific section where the usage of a particular USB port is defined or configured. For instance, the CH32V307 microcontroller has two separate USB instances, but the code does not seem to indicate any preference or configuration for selecting either of these USB ports.

**Comment by sakumisu** [comment]
compiling one port c source means using this port , no need to select

**Comment by aurimasniekis** [comment]
@sakumisu, thank you for your response. I understand that compiling one port's C source means using that port. However, I'm interested in running multiple USB ports simultaneously. Is there a way to modify or configure the code so that both USB instances on the CH32V307 microcontroller can be used at the same time? Any guidance or suggestions would be greatly appreciated.

**Comment by HaiMianBBao** [comment]
You can use two USB peripherals, but you cannot use these two USB peripherals as both hosts or devices. You can use one USB as the host and the other USB as the device.

**Comment by aurimasniekis** [comment]
Is that limitation of library or MCU?

**Comment by HaiMianBBao** [comment]
Limitation of  library.

**Comment by sakumisu** [comment]
> @sakumisu, thank you for your response. I understand that compiling one port's C source means using that port. However, I'm interested in running multiple USB ports simultaneously. Is there a way to modify or configure the code so that both USB instances on the CH32V307 microcontroller can be used at the same time? Any guidance or suggestions would be greatly appreciated.

Support in the future.
