### ISSUE TITLE
Compiling RISC-V toolchain

### ISSUE THREAD

**Issue by Xelus22** [CherryUSB/cherryusb_wch#7]
Hi i am having an issue trying to compile HID_MOUSE example

![image](https://github.com/CherryUSB/cherryusb_wch/assets/17491233/b8026846-acfe-411d-8fda-bf61a4003cf1)

I am using this.
https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack

I have also changed the toolchain prefix to 
![image](https://github.com/CherryUSB/cherryusb_wch/assets/17491233/d50a9253-b91f-408a-8cf0-3ecd01db0f0b)

**Comment by Xelus22** [comment]
Fixed by using the old compiler. This is a newer version of the riscv compiler. Anyone in future use the `riscv-none-embed` though it is deprecated.

**Comment by Xelus22** [comment]
![image](https://github.com/CherryUSB/cherryusb_wch/assets/17491233/0cf6a6e4-a5e1-4915-b8c3-7f46f824a6ab)

Cannot compile due to these issues

I am using this toolchain https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack

**Comment by sakumisu** [comment]
No, you must use toolchain that wch provided.

**Comment by Xelus22** [comment]
Thanks @sakumisu , now the issue is `sleep_ms` is undefined reference?

![image](https://github.com/CherryUSB/cherryusb_wch/assets/17491233/e9e1a56d-c9a9-49b0-aa30-c351056f81b6)

**Comment by sakumisu** [comment]
Just delete.
